FROM rust:latest as BUILDER

# Install base dependencies
RUN apt-get update \
    && apt-get install -y -q \
        libpq-dev \
        libssl-dev \
        libsasl2-dev \
        libzmq3-dev \
        openssl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN USER=root cargo new --bin daemon
WORKDIR /daemon

COPY ./daemon/Cargo.toml ./Cargo.toml
RUN cargo build --release

RUN rm src/*.rs
COPY ./daemon/src ./src

RUN rm ./target/release/gridd* ./target/release/deps/gridd*
RUN cargo build --release

# create the standalone image
FROM alpine

RUN apk update \
    && apk add --no-cache \
        libssl1.1 \
        libzmq && \
    rm -rf /var/cache/apk/*

COPY --from=BUILDER /daemon/target/release/gridd /

CMD ["/gridd"]
